# config.py

# Email settings
SENDER_EMAIL = "firstlineimpor2@gmail.com"  # Your Gmail address
SENDER_PASSWORD = "ovof wvyj jfva wmsm"     # App password generated by Gmail
RECIPIENT_EMAIL = "smby1985@gmail.com"      # Recipient email address

# Time window in minutes for considering posts as "new"
TIME_WINDOW_MINUTES = 60  # Example: 1 day

# Forum search links with titles
SEARCH_LINKS = [
    {"title": "tikka", "url": "https://www.snipershide.com/shooting/search/7218891/?q=tikka+6.5&t=post&c[child_nodes]=1&c[nodes][0]=36&c[title_only]=1&o=date"},
    {"title": "scope", "url": "https://www.snipershide.com/shooting/search/7218893/?q=mark++5hd&t=post&c[child_nodes]=1&c[nodes][0]=36&c[title_only]=1&o=date"},
    {"title": "annealer", "url": "https://www.snipershide.com/shooting/search/7218894/?q=amp+annealer&t=post&c[child_nodes]=1&c[nodes][0]=36&c[title_only]=1&o=date"}
    # Add more links as needed
] 