# config.py

# Email settings
SENDER_EMAIL = "firstlineimpor2@gmail.com"  # Your Gmail address
SENDER_PASSWORD = "ovof wvyj jfva wmsm"     # App password generated by Gmail
RECIPIENT_EMAIL = "smby1985@gmail.com"      # Recipient email address